#travis configuration for testing
language: cpp


# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cmake
  - ./33WeightGraph

